export default {
  CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
  UPDATE_CARD_SUCCESS: 'UPDATE_CARD_SUCCESS',
  LOAD_CARDS_SUCCESS: 'LOAD_CARDS_SUCCESS',
  LOAD_CARD_FRAMES_SUCCESS: 'LOAD_CARD_FRAMES_SUCCESS',
  ORDER_CARDS: 'ORDER_CARDS',
  DELETE_CARD_OPTIMISTIC: 'DELETE_CARD_OPTIMISTIC',
  BEGIN_API_CALL: 'BEGIN_API_CALL',
  API_CALL_ERROR: 'API_CALL_ERROR',
  // CREATE_DECK: 'CREATE_DECK',
  // UPDATE_DECK: 'UPDATE_DECK',
  // LOAD_DECKS: 'LOAD_DECKS',
  // DELETE_DECK: 'DELETE_DECK',
};
